force-app/main/default/objects/DRL_UTMSource__mdt/DRL_UTMSource__mdt.object-meta.xml
force-app/main/default/objects/DRL_UTMSource__mdt/fields/LeadSource__c.field-meta.xml
force-app/main/default/objects/DRL_UTMSource__mdt/fields/Name__c.field-meta.xml
manifest/package.xml

Custom Metadata Type: UTM Source
Fields:
Name (Standard) (Text)
Lead Source (Text)

DRL-47-dev-(UTM Custom metadata object)

---

force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPage.cmp
force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPage.cmp-meta.xml
force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPage.css
force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPage.design
force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageController.js
force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPageHelper.js

DRL-7 : On Adding Contact to opportunity on the contact lookup field.
Made changes in **API_Plus_New_OpportunityPage.cmp**

DRL-7 : On Adding Contact to opportunity on the contact lookup field.

---

force-app/main/default/aura/API_Plus_New_OpportunityPage/API_Plus_New_OpportunityPage.cmp

Added Contact Lookup as Mandatory.

DRL-7 : Contact Lookup(Mandatory)

---

force-app/main/default/flows/DRL_ContactRoleRecordCreation.flow-meta.xml
force-app/main/default/triggers/Populate_Opportunity_stage_tracker.trigger
manifest/package.xml

Bug - Duplicate Contact role record creation
fixture - Deactivated DRL_ContactRoleRecordCreation Flow, Added Insertion DML statement on Populate_Opportunity_stage_tracker Tigger(Existing)

Drl 88 bug

---

force-app/main/default/classes/DRL_UpdatePotentialAtLaunchBatch.cls
force-app/main/default/flows/DRL_CalculatePotentialAtLaunchOnOpportunity.flow-meta.xml
manifest/package.xml

Added the 'API' record type for both flow and batch class which is calculating  Potential at Launch field

Added API Record Type In Batch Class and Flow

---

force-app/main/default/classes/DRL_CampaignInfluenceTriggerHelper.cls
force-app/main/default/classes/DRL_CampaignInfluenceTriggerHelper.cls-meta.xml
force-app/main/default/classes/DRL_CampaignInfluenceTriggerHelperTest.cls-meta.xml
force-app/main/default/classes/DRL_LeadTriggerHelper.cls

Added xml files

---

force-app/main/default/aura/DRL_ConvertLeadOpportunitySection/DRL_ConvertLeadOpportunitySection.cmp
force-app/main/default/aura/DRL_ConvertLeadOpportunitySection/DRL_ConvertLeadOpportunitySection.css
force-app/main/default/aura/DRL_ConvertLeadOpportunitySection/DRL_ConvertLeadOpportunitySectionController.js
force-app/main/default/aura/DRL_ConvertLeadOpportunitySection/DRL_ConvertLeadOpportunitySectionHelper.js
force-app/main/default/aura/DRL_ConvertLeadProspect/DRL_ConvertLeadProspect.cmp
force-app/main/default/aura/DRL_ConvertLeadProspect/DRL_ConvertLeadProspectHelper.js
force-app/main/default/aura/DRL_ConvertLeadRunAutomationSection/DRL_ConvertLeadRunAutomationSection.css
force-app/main/default/aura/DRL_LeadConvertSuccessSection/DRL_LeadConvertSuccessSection.cmp
force-app/main/default/aura/DRL_LeadConvertSuccessSection/DRL_LeadConvertSuccessSection.css
force-app/main/default/aura/DRL_ProspectRelatedChildLeads/DRL_ProspectRelatedChildLeads.cmp
force-app/main/default/aura/DRL_ProspectRelatedChildLeads/DRL_ProspectRelatedChildLeadsHelper.js
force-app/main/default/aura/DRL_convertLeadAccountSection/DRL_convertLeadAccountSection.cmp
force-app/main/default/aura/DRL_convertLeadAccountSection/DRL_convertLeadAccountSectionController.js
force-app/main/default/aura/DRL_convertLeadAccountSection/DRL_convertLeadAccountSectionHelper.js
force-app/main/default/aura/DRL_convertLeadContactSection/DRL_convertLeadContactSection.cmp
force-app/main/default/aura/DRL_convertLeadContactSection/DRL_convertLeadContactSectionController.js
force-app/main/default/aura/DRL_convertLeadContactSection/DRL_convertLeadContactSectionHelper.js
force-app/main/default/campaignInfluenceModels/DRL_APICampaignsDistributionModel.campaignInfluenceModel-meta.xml
force-app/main/default/classes/DRL_ConvertLeadProspectController.cls
force-app/main/default/classes/DRL_convertLeadProspectTest.cls
force-app/main/default/layouts/DRL_UTMSource__mdt-UTM Source Layout.layout-meta.xml
force-app/main/default/layouts/Lead-Prospect.layout-meta.xml

error handling and styling bugs

---

force-app/main/default/aura/leadSalesPath/leadSalesPath.cmp
force-app/main/default/aura/leadSalesPath/leadSalesPathController.js
force-app/main/default/classes/DRL_ConvertLeadProspectController.cls
force-app/main/default/objects/Lead/validationRules/DRL_ConvertedLeadStatusCannotbeUpdated.validationRule-meta.xml
manifest/package.xml

DRL-113
Convert parent prospect if not converted

DRL-113 and convertprospectalongwithlead

---

force-app/main/default/aura/leadSalesPath/leadSalesPath.cmp
force-app/main/default/aura/leadSalesPath/leadSalesPathController.js

DRL-118- fix:reset standard lightning:picklistpath component

resetstandardcpathcomponent

---

force-app/main/default/classes/DRL_ConvertLeadProspectController.cls

DRL-115- updated error message when duplicate value found

updated error message when duplicate value found

---

force-app/main/default/aura/DRL_convertLeadContactSection/DRL_convertLeadContactSectionHelper.js
force-app/main/default/aura/leadSalesPath/leadSalesPathController.js
force-app/main/default/objects/Contact/fieldSets/ConvertLeadContact.fieldSet-meta.xml

resetopenPopupAttribute

---

force-app/main/default/layouts/Lead-Prospect.layout-meta.xml
force-app/main/default/objects/Lead/businessProcesses/Prospect Process.businessProcess-meta.xml

Added recordtype field on prospect layout

recordtype added on prospect layout

---

ReleaseNotes.txt
force-app/main/default/classes/DRL_LeadTriggerHelper.cls

-Do not make country field null
-Make country field required on Lead layout

do not make country field null on Lead

---

force-app/main/default/classes/LeadReminderEmailSchedulerTest.cls
force-app/main/default/classes/LeadReminderEmailSchedulerTest.cls-meta.xml
manifest/package.xml

LeadReminderEmailScheduler class coverage

test class converage

---

force-app/main/default/aura/DRL_convertLeadContactSection/DRL_convertLeadContactSectionHelper.js
force-app/main/default/classes/DRL_ConvertLeadProspectController.cls

restrict contact update if prospect converted

---

force-app/main/default/profiles/Admin.profile-meta.xml
force-app/main/default/profiles/Marketing Manager User with Account Creation Permissions.profile-meta.xml
force-app/main/default/profiles/Marketing Manager User.profile-meta.xml

removed RT access for admin and marketing profiles

---

force-app/main/default/classes/DRL_LeadTriggerHelper.cls
force-app/main/default/customMetadata/DRL_ProspectLeadStatusMapping.CMDDRL0002.md-meta.xml

Changes updated in Apex class and Metadata

Fix for DRl-36

---

force-app/main/default/classes/OpportunityControllerTest.cls
force-app/main/default/classes/OpportunityControllerTest.cls-meta.xml
force-app/main/default/classes/opportunityAPITest.cls
force-app/main/default/classes/opportunityAPITest.cls-meta.xml
manifest/package.xml

- OpportunityControllerTest - OpportunityController (100%)
- opportunityAPITest - 1) opportunityAPI (79%)
2) OpportunityNewController(100%)

DRL-129 : Test Class Coverage

---

force-app/main/default/classes/AccountTeamAccessHelperTest.cls
force-app/main/default/classes/CampaignMemberStatusTest.cls
force-app/main/default/classes/OpportunityJourneyHandler2Test.cls
force-app/main/default/triggers/campaignInfluenceAttributes.trigger
manifest/package.xml

DRL_CampaignInfluenceTriggerHelper- (Added campaignInfluenceAttributes trigger only)
CampaignMemberStatus
OpportunityJourneyHandler2
AccountTeamAccess

DRL-131- (DRL_CampaignInfluenceTriggerHelper

---

force-app/main/default/classes/DRL_OpportunityTriggerHelperTest.cls
force-app/main/default/classes/LeadTriggerHandlerTest.cls
force-app/main/default/classes/LeadTriggerHandlerTest.cls-meta.xml
manifest/package.xml

LeadTriggerHandlerTest
DRL_OpportunityTriggerHelperTest

DRL-128 - Changes done in following test classes

---

force-app/main/default/classes/DRLUtilTest.cls-meta.xml
force-app/main/default/classes/DRL_convertLeadProspectTest.cls

DRL-149; issure raised as we have removed prospect recordtype access. prospect RT record creation removed

prospect record creation removed

---

force-app/main/default/classes/DRL_LeadTriggerHelper.cls

changes for DRL-150

---

ReleaseNotes.txt
force-app/main/default/classes/DRL_LeadCleanupBatch.cls
force-app/main/default/classes/DRL_LeadCleanupBatch.cls-meta.xml
force-app/main/default/classes/DRL_LeadCleanupBatchTest.cls
force-app/main/default/classes/DRL_LeadCleanupBatchTest.cls-meta.xml
force-app/main/default/objects/Lead/fields/DRL_IsProspect__c.field-meta.xml
force-app/main/default/profiles/Admin.profile-meta.xml
manifest/package.xml

Lead Cleanup Batch

---

force-app/main/default/classes/AccountTeamAccessHelperTest.cls
force-app/main/default/classes/DRLUtilTest.cls
force-app/main/default/classes/DRL_LeadTriggerHelper.cls
force-app/main/default/classes/DRL_LeadTriggerHelperTest.cls

update email on lead on insertion with prospect selected and standard email populated

update email on lead on insertion

---

force-app/main/default/triggers/Populate_Opportunity_stage_tracker.trigger

primary contact role bug - update existing contact role as primary

primarycontactbug
